### ISSUE TITLE
WHIP: prepare version 2.0

### ISSUE THREAD

**Issue by enricobattocchi** [Yoast/whip#156]
```[tasklist]
### Tasks
- [x] https://github.com/Yoast/whip/pull/157
- [x] improve documentation about BC 
- [x] https://github.com/Yoast/whip/pull/159
- [x] https://github.com/Yoast/whip/pull/160
- [ ] https://github.com/Yoast/whip/pull/161
```
